### ISSUE TITLE
relation.js

### ISSUE THREAD

**Issue by miche101** [osm-ToniE/ptna-www#46]
Hi Toni,

ich hab mal versucht die Relationsanalyse schneller zu machen. Glaub das Problem ist das zu viele DOM Aktionen stattfinden.. zu oft .innerHTML

Ich hab in der Datei die Funktion handleMember() ersetzt und addtable() zusätzlich erstellt. Faktor 40x schneller.. ich hab die Funktion handleMember() vereinfacht.. und ein paar Sachen rausgenommen.. die ich als unnötig finde ;-) Musst du wissen.. die alte Funktion ist sehr kompliziert, darum hab ich sie ersetzt. Vielleicht braucht man ein paar Sachen auch nicht mehr wenn es so schnell jetzt läuft. 

script/relation.js

[patch.js.txt](https://github.com/osm-ToniE/ptna-www/files/10888224/patch.js.txt)

**Comment by osm-ToniE** [comment]
Danke Miche,

Danke für den Hinweis.

Die häufige Verwendung (jeweils pro 'member') von `document.getElementById(match+"-members").innerHTML += html;` trägt sicherlich signifikant zur Trägheit des Programms bei. Das werde ich mal optimieren, ohne den restlichen Code zu ändern.

Der Einsatz von `setTimeout( handleMember, 0, relation_id, index );` zum Re-Scheduling trägt auch zur Trägheit bei. Das habe ich eingebaut, weil der Web-Browser sonst bei langen Routen (Flixbus, ICE, ...) nicht mehr reagierte. Das Fenster/der Tab des Browsers ist so lange blockiert bis `handleMember( relation_id, index )` fertig ist. Es wurden so lange  keine Maus- und Tastatur-Eingaben verarbeitet. Im derzeitigen Code haben Maus- und Tastatur-Eingaben nach 5 'members' die Chance abgearbeitet zu werde, `handleMember()` beendet sich und lässt solche Events vor, was das Browser-Fenster/den Tab reaktionsfähig erscheinen lässt. Die Analyse wird dadurch aber auch ganz schön ausgebremst.

Vielleicht kann ich mit deinem Hinweis die Zahl '5' auf '20'?

**Comment by Strubbl** [comment]
Der teure Aufruf ist doch scheinbar `document.getElementById(match+"-members").innerHTML += html;`, oder? Weil der so oft stattfindet und dauert.

Kann man die HTML-Änderungen (Tabellenzeilen hinzufügen) nicht pro `match` einsammeln und am Ende nach der for-Loop einmal je `match` den `innerHTML` aktualisieren? Das würde doch eine Menge get/set innerHTML-Aufrufe vermeiden und vor allem die 8 Sekunden Garbage Collection (von insgesamt ca. 43 s) bei zB. dem Aufruf von ICE 1 (https://ptna.openstreetmap.de/relation.php?id=6188945&lang=de) stark reduzieren.

**Comment by miche101** [comment]
ja genau.. glaub das ist die teure Aktion. Wenn man alles beim alten lassen will dann wäre es... das man die ganze tabelleninhalt in ein array packt um am ende einmal schreibt das schnellste.

**Comment by miche101** [comment]
jetzt hab es mal in eine min Änderung gemacht.. 

Bei handleMember() 
 - .innerHTML entfernt und dafür ein array erstellt
 - if... für jede Tabelle .push

Global:
vier Arrays definiert: var htmltable...

NEUE Funktion zum erstellen und hinzufügen der Tabelle addtable() 

Das macht dann aus > 1000 innerHTML aufrufe ... 4 Stück :-) bei der ICE Strecke
[patch.js.txt](https://github.com/osm-ToniE/ptna-www/files/10892095/patch.js.txt)

**Comment by miche101** [comment]
Macht aus der ICE strecke bei mir ca. 58 Sekunden... dann 3 Sekunden 8-)

**Comment by osm-ToniE** [comment]
Hallo Miche, Sven,

in der Tat, über das `document.getElementById(match+"-members").innerHTML += html;` habe ich mir bei der Erstellung des Code sträflicherweise keine Gedanken gemacht.

Miche, dein letzter Vorschlag scheint die Lösung zu sein. Das werde ich mal einbauen - liege aber gerade mit Erkältung flach.

BTW:

`        //                if ( match == "route" ) {
        //                    html += "    <td class=\"symbol\"><img src=\"/img/" + wayimg + ".png\" width=\"32\" height=\"32\"></td>";
        //                }
`
Ist noch eine Idee, Lücken in der Route so darzustellen, wie es JOSM im Relationseditor macht. Aber der Code lief ja soooo langsam, dass ich das nicht auch noch machen wollte.

**Comment by miche101** [comment]
ich hab mal meinen Code mit Flixbus getestet... Relation 11817492 *g* 7395 Ways... in 21 Sekunden

... von Bukarest bis Brüssel

**Comment by miche101** [comment]
> liege aber gerade mit Erkältung flach.

gute Besserung!

**Comment by miche101** [comment]
>Relation 11817492 g 7395 Ways... in 21 Sekunden

Meiner erste Version.. schafft die Strecke ... von Bukarest bis Brüssel in 6-7Sekunden krass

**Comment by osm-ToniE** [comment]
Danke Miche, das ist super!

Ich habe den 'timeout' so eingestellt, dass das Re-Scheduling erst nach 10.000 Member kommt (also fast nie).
Der FlixBus von Brüssel nach Bukarest braucht jetzt nur noch **745ms** - echt krass: Danke!

**Comment by Strubbl** [comment]
Stark, miche! :muscle: 

Ich freue mich schon, wenn der Code live ist. :partying_face:

**Comment by osm-ToniE** [comment]
Ist seit 17:06 online, Ihr müsst auf relation.php evtl. Ctrl-R oder Ctrl-F5 machen, um relation.js neu in den Browser Cache zu laden.

Danke nochmals: Miche.

**Comment by Strubbl** [comment]
Wow, ICE 1 lädt quasi augenblicklich. :+1:

**Comment by miche101** [comment]
bitte bitte.. :) vielleicht schreib ich noch was dazu.. wenn ich jetzt schonmal weiss wie die Sache arbeitet.

Gruß Miche
